<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musicos [
<!ELEMENT musicos (musico*)>
<!ELEMENT musico ((nombre, apodo), fechaNacimiento)><!--habÃ­a puesto un OR, y no funcionaba porque los dos estaban puestos, he puesto una coma instead.-->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apodo (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
]>
<musicos>
<musico>
<nombre>Antonio Vivaldi</nombre>
<apodo>El cura pelirrojillo</apodo>
<fechaNacimiento>4 de marzo de 1678</fechaNacimiento>
</musico>
<musico>
<nombre>Johann Sebastian Bach</nombre>
<apodo>El viejo peluca</apodo>
<fechaNacimiento>21 de marzo de 1685</fechaNacimiento>
</musico>
</musicos>