<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
<!ELEMENT agenda (contacto*)>
<!ELEMENT contacto (nombre, telefonoFijo*, telefonoMovil*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefonoFijo (#PCDATA)>
<!ELEMENT telefonoMovil (#PCDATA)>
]>
<agenda>
<contacto>
<nombre>Ayuntamiento</nombre>
<telefonoFijo>010</telefonoFijo><!--el telefono movil estaba puesto en +, entonces era obligatorio, lo he puesto en *-->
</contacto>
<contacto>
<nombre>Emergencias</nombre>
<telefonoFijo>112 (Uni√≥n Europea)</telefonoFijo>
<telefonoFijo>911 (Estados Unidos)</telefonoFijo><!--este registro estaba en el orden equivocado.-->
<telefonoMovil>Desconocido</telefonoMovil>

</contacto>
</agenda>